import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/Work.module.css";

export default function Details({ project }) {
  let homepage = "";
  let language = "";
  let date = new Date(project["created_at"]);
  let dateString = date.toLocaleDateString();
  if (project.homepage) {
    homepage = "Homepage: " + project.homepage;
  }
  if (project.language) {
    language = "Language: " + project.language;
  }
  return (
    <>
      <Head>
        <title>Madd | {project.name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.workDetails}>
        <h2>Project Details</h2>
        <h3>{project.name}</h3>
        <div>
          <Image
            src={project.owner.avatar_url}
            alt={project.name}
            width={260}
            height={260}
          />
        </div>
        <p>{homepage}</p>
        <p>Description: {project.description}</p>
        <p>Created at: {dateString}</p>
        <p>{language}</p>
        <p>URL: {project.url}</p>
      </div>
    </>
  );
}

export async function getStaticPaths() {
  const resp = await fetch(
    "https://api.github.com/search/repositories?q=website&page=3&per_page=16&sort=stars&order=desc"
  );
  const value = await resp.json();

  const paths = value.items.map((item) => {
    return {
      params: { id: item.id.toString() },
    };
  });

  return {
    paths,
    fallback: false,
  };
}

export async function getStaticProps(context) {
  const id = context.params.id;
  const response = await fetch("https://api.github.com/repositories/" + id);
  const data = await response.json();

  if (!data) {
    return {
      notFound: true,
    };
  }
  return {
    props: {
      project: data,
    },
  };
}
