import Link from "next/link";
import Head from "next/head";
import styles from "../../styles/Work.module.css";
import WorkCard from "../../components/WorkCard";

export default function projects({ projects }) {
  return (
    <div>
      <Head>
        <title>Madd | Work</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h2>Our Work</h2>
      <ul className={styles.workList}>
        {projects.map((project) => (
          <li key={project.id}>
            <Link href={"/work/" + project.id}>
              <WorkCard project={project} />
            </Link>
          </li>
        ))}
      </ul>
    </div>
  );
}

export async function getStaticProps() {
  const resp = await fetch(
    "https://api.github.com/search/repositories?q=website&page=3&per_page=16&sort=stars&order=desc"
  );
  const data = await resp.json();
  if (!data) {
    return {
      notFound: true,
    };
  }
  return {
    props: {
      projects: data.items,
    },
  };
}
