import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Madd</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <header>
          <h2 className={styles.title}>Bring your ideas to life</h2>
          <p className={styles.description}>We create best digital products.</p>
          <button>Get Started</button>
        </header>
        <section>
          <h3 className={styles.heading}>
            We are leaders in web and mobile design and development.
          </h3>
          <p className={styles.description}>
            We create websites, applications, 3D design, motion design and
            animation. We bring the most daring ideas to life.
          </p>
        </section>
      </main>
    </div>
  );
}
