import { useTeam } from "../context/teamContext";
import TeamCard from "../components/TeamCard";
import Head from "next/head";
import styles from "../styles/Team.module.css";

function Team() {
  const [team] = useTeam();
  return (
    <>
      <Head>
        <title>Madd | Team</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h2 className={styles.heading}>Our Team</h2>
      <ul className={styles.teamList}>
        {team.map((item) => (
          <li key={item.id}>
            <TeamCard item={item} />
          </li>
        ))}
      </ul>
    </>
  );
}

export default Team;
