import { useTeam } from "../context/teamContext";
import Card from "../components/Card";
import Head from "next/head";
import styles from "../styles/Team.module.css";

function Team() {
  const [team] = useTeam();
  return (
    <>
      <Head>
        <title>Madd Team</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.teamList}>
        {team.map((item) => (
          <Card key={item.id} item={item} />
        ))}
      </div>
    </>
  );
}

export default Team;
